# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.25.0/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.25.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/samraatgupta/Desktop/PBD-2d-sim-main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/samraatgupta/Desktop/PBD-2d-sim-main

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.23.1_1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.25.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.25.0/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.25.0/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.25.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.25.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.25.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.25.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/samraatgupta/Desktop/PBD-2d-sim-main/CMakeFiles /Users/samraatgupta/Desktop/PBD-2d-sim-main//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/samraatgupta/Desktop/PBD-2d-sim-main/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Simulation2D_RESOURCES-dependencies

# Build rule for target.
Simulation2D_RESOURCES-dependencies: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Simulation2D_RESOURCES-dependencies
.PHONY : Simulation2D_RESOURCES-dependencies

# fast build rule for target.
Simulation2D_RESOURCES-dependencies/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Simulation2D_RESOURCES-dependencies.dir/build.make CMakeFiles/Simulation2D_RESOURCES-dependencies.dir/build
.PHONY : Simulation2D_RESOURCES-dependencies/fast

#=============================================================================
# Target rules for targets named magnum-PBD2d

# Build rule for target.
magnum-PBD2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 magnum-PBD2d
.PHONY : magnum-PBD2d

# fast build rule for target.
magnum-PBD2d/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magnum-PBD2d.dir/build.make CMakeFiles/magnum-PBD2d.dir/build
.PHONY : magnum-PBD2d/fast

DrawableObjects/ParticleGroup2D.o: DrawableObjects/ParticleGroup2D.cpp.o
.PHONY : DrawableObjects/ParticleGroup2D.o

# target to build an object file
DrawableObjects/ParticleGroup2D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magnum-PBD2d.dir/build.make CMakeFiles/magnum-PBD2d.dir/DrawableObjects/ParticleGroup2D.cpp.o
.PHONY : DrawableObjects/ParticleGroup2D.cpp.o

DrawableObjects/ParticleGroup2D.i: DrawableObjects/ParticleGroup2D.cpp.i
.PHONY : DrawableObjects/ParticleGroup2D.i

# target to preprocess a source file
DrawableObjects/ParticleGroup2D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magnum-PBD2d.dir/build.make CMakeFiles/magnum-PBD2d.dir/DrawableObjects/ParticleGroup2D.cpp.i
.PHONY : DrawableObjects/ParticleGroup2D.cpp.i

DrawableObjects/ParticleGroup2D.s: DrawableObjects/ParticleGroup2D.cpp.s
.PHONY : DrawableObjects/ParticleGroup2D.s

# target to generate assembly for a file
DrawableObjects/ParticleGroup2D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magnum-PBD2d.dir/build.make CMakeFiles/magnum-PBD2d.dir/DrawableObjects/ParticleGroup2D.cpp.s
.PHONY : DrawableObjects/ParticleGroup2D.cpp.s

PBDSolver/PBDSolver2D.o: PBDSolver/PBDSolver2D.cpp.o
.PHONY : PBDSolver/PBDSolver2D.o

# target to build an object file
PBDSolver/PBDSolver2D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magnum-PBD2d.dir/build.make CMakeFiles/magnum-PBD2d.dir/PBDSolver/PBDSolver2D.cpp.o
.PHONY : PBDSolver/PBDSolver2D.cpp.o

PBDSolver/PBDSolver2D.i: PBDSolver/PBDSolver2D.cpp.i
.PHONY : PBDSolver/PBDSolver2D.i

# target to preprocess a source file
PBDSolver/PBDSolver2D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magnum-PBD2d.dir/build.make CMakeFiles/magnum-PBD2d.dir/PBDSolver/PBDSolver2D.cpp.i
.PHONY : PBDSolver/PBDSolver2D.cpp.i

PBDSolver/PBDSolver2D.s: PBDSolver/PBDSolver2D.cpp.s
.PHONY : PBDSolver/PBDSolver2D.s

# target to generate assembly for a file
PBDSolver/PBDSolver2D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magnum-PBD2d.dir/build.make CMakeFiles/magnum-PBD2d.dir/PBDSolver/PBDSolver2D.cpp.s
.PHONY : PBDSolver/PBDSolver2D.cpp.s

Shaders/ParticleSphereShader2D.o: Shaders/ParticleSphereShader2D.cpp.o
.PHONY : Shaders/ParticleSphereShader2D.o

# target to build an object file
Shaders/ParticleSphereShader2D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magnum-PBD2d.dir/build.make CMakeFiles/magnum-PBD2d.dir/Shaders/ParticleSphereShader2D.cpp.o
.PHONY : Shaders/ParticleSphereShader2D.cpp.o

Shaders/ParticleSphereShader2D.i: Shaders/ParticleSphereShader2D.cpp.i
.PHONY : Shaders/ParticleSphereShader2D.i

# target to preprocess a source file
Shaders/ParticleSphereShader2D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magnum-PBD2d.dir/build.make CMakeFiles/magnum-PBD2d.dir/Shaders/ParticleSphereShader2D.cpp.i
.PHONY : Shaders/ParticleSphereShader2D.cpp.i

Shaders/ParticleSphereShader2D.s: Shaders/ParticleSphereShader2D.cpp.s
.PHONY : Shaders/ParticleSphereShader2D.s

# target to generate assembly for a file
Shaders/ParticleSphereShader2D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magnum-PBD2d.dir/build.make CMakeFiles/magnum-PBD2d.dir/Shaders/ParticleSphereShader2D.cpp.s
.PHONY : Shaders/ParticleSphereShader2D.cpp.s

Simulation2DExample.o: Simulation2DExample.cpp.o
.PHONY : Simulation2DExample.o

# target to build an object file
Simulation2DExample.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magnum-PBD2d.dir/build.make CMakeFiles/magnum-PBD2d.dir/Simulation2DExample.cpp.o
.PHONY : Simulation2DExample.cpp.o

Simulation2DExample.i: Simulation2DExample.cpp.i
.PHONY : Simulation2DExample.i

# target to preprocess a source file
Simulation2DExample.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magnum-PBD2d.dir/build.make CMakeFiles/magnum-PBD2d.dir/Simulation2DExample.cpp.i
.PHONY : Simulation2DExample.cpp.i

Simulation2DExample.s: Simulation2DExample.cpp.s
.PHONY : Simulation2DExample.s

# target to generate assembly for a file
Simulation2DExample.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magnum-PBD2d.dir/build.make CMakeFiles/magnum-PBD2d.dir/Simulation2DExample.cpp.s
.PHONY : Simulation2DExample.cpp.s

resource_Simulation2D_RESOURCES.o: resource_Simulation2D_RESOURCES.cpp.o
.PHONY : resource_Simulation2D_RESOURCES.o

# target to build an object file
resource_Simulation2D_RESOURCES.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magnum-PBD2d.dir/build.make CMakeFiles/magnum-PBD2d.dir/resource_Simulation2D_RESOURCES.cpp.o
.PHONY : resource_Simulation2D_RESOURCES.cpp.o

resource_Simulation2D_RESOURCES.i: resource_Simulation2D_RESOURCES.cpp.i
.PHONY : resource_Simulation2D_RESOURCES.i

# target to preprocess a source file
resource_Simulation2D_RESOURCES.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magnum-PBD2d.dir/build.make CMakeFiles/magnum-PBD2d.dir/resource_Simulation2D_RESOURCES.cpp.i
.PHONY : resource_Simulation2D_RESOURCES.cpp.i

resource_Simulation2D_RESOURCES.s: resource_Simulation2D_RESOURCES.cpp.s
.PHONY : resource_Simulation2D_RESOURCES.s

# target to generate assembly for a file
resource_Simulation2D_RESOURCES.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magnum-PBD2d.dir/build.make CMakeFiles/magnum-PBD2d.dir/resource_Simulation2D_RESOURCES.cpp.s
.PHONY : resource_Simulation2D_RESOURCES.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Simulation2D_RESOURCES-dependencies"
	@echo "... magnum-PBD2d"
	@echo "... DrawableObjects/ParticleGroup2D.o"
	@echo "... DrawableObjects/ParticleGroup2D.i"
	@echo "... DrawableObjects/ParticleGroup2D.s"
	@echo "... PBDSolver/PBDSolver2D.o"
	@echo "... PBDSolver/PBDSolver2D.i"
	@echo "... PBDSolver/PBDSolver2D.s"
	@echo "... Shaders/ParticleSphereShader2D.o"
	@echo "... Shaders/ParticleSphereShader2D.i"
	@echo "... Shaders/ParticleSphereShader2D.s"
	@echo "... Simulation2DExample.o"
	@echo "... Simulation2DExample.i"
	@echo "... Simulation2DExample.s"
	@echo "... resource_Simulation2D_RESOURCES.o"
	@echo "... resource_Simulation2D_RESOURCES.i"
	@echo "... resource_Simulation2D_RESOURCES.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

